### ISSUE TITLE
Error Calling & Unsupported Device Error

### ISSUE THREAD

**Issue by iokobi** [z3ntu/homebrew-openrazer#1]
Thanks so much for starting this project for macOS users. I was able to install using brew but I get the error below when I run `razer_test --verbose`

    [info] razer_test - version 0.0.1
    [critical] Error calling IOCreatePlugInInterfaceForService. kr: -536870210
    [debug] Ignored interface with number: 1
    [warning] Device with the USB ID 1532:0228 (Razer BlackWidow Elite) is not supported.
    [debug] Ignored interface with number: 2
    [info] Initialization finished. D-Bus interface is active...

Any idea if BalckWidow Elite will be supported or not.

Thanks again for this.

**Comment by z3ntu** [comment]
There's a PR open for the BlackWidow Elite: https://github.com/z3ntu/razer_test/pull/1 . Closing this as it's not related to the Homebrew package.
